//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqCache.Test.Contexts.EntityFrameworkDatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityFrameworkDatabaseFirstContext : DbContext
    {
        public EntityFrameworkDatabaseFirstContext()
            : base("name=EntityFrameworkDatabaseFirstContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestTable1DatabaseFirst> TestTable1DatabaseFirst { get; set; }
    }
}
